<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$text ='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ante diam, lacinia eget volutpat nec, ultricies quis velit. Sed vestibulum mauris eget nisi sollicitudin, in sagittis nunc sodales. Vestibulum rhoncus iaculis semper. In ac sagittis ligula, convallis volutpat lorem. In convallis in eros et pretium. Duis vel urna lectus. Integer non tortor tincidunt, suscipit neque vel, gravida enim. Pellentesque sit amet venenatis massa, eget aliquet ligula. Nullam a accumsan sem, molestie imperdiet mi. Proin lorem orci, sagittis quis rhoncus et, vehicula commodo quam. Aenean tempus enim nec fermentum tempus. Integer turpis odio, vestibulum id maximus ac, efficitur posuere dui. Maecenas lorem dolor, feugiat quis lectus eget, fringilla mollis dolor. Vivamus pretium mollis molestie. Aenean maximus turpis vel ex aliquam, bibendum imperdiet odio finibus.

Fusce scelerisque dui et sapien rhoncus, in tristique tortor efficitur. Donec at tincidunt elit. Integer interdum diam quis viverra tristique. Donec elementum libero sed orci viverra, at porttitor dui posuere. Etiam facilisis dui nisl, quis egestas felis egestas sit amet. In ullamcorper, risus tristique faucibus sodales, est tellus vestibulum elit, eget egestas risus ipsum et nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer a enim scelerisque, vestibulum velit ut, feugiat quam.

Cras sed odio ipsum. In eu lectus nec velit aliquam facilisis. Ut mattis velit ut pharetra rhoncus. Cras dictum eget ex ac malesuada. Mauris quis leo ullamcorper, varius nisi non, mollis eros. Proin iaculis dui sit amet dolor dignissim, a accumsan leo elementum. In tincidunt ligula at sapien sodales sollicitudin. Donec elit ante, ultricies in rutrum nec, varius ac arcu. Nulla ornare pulvinar nisi vel efficitur. Nam tincidunt aliquet ante, cursus iaculis lorem ornare ut. Maecenas sed porta massa, sit amet ultricies dolor. Mauris id arcu arcu. Vestibulum luctus congue mauris, quis molestie nibh varius vel. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque imperdiet id arcu non cursus.

Nunc sed urna condimentum, vestibulum sem at, rhoncus arcu. Vestibulum blandit sagittis massa in suscipit. Nam pharetra eleifend placerat. Praesent ultrices vel lacus ac egestas. Aliquam pulvinar efficitur dui, nec hendrerit mauris porttitor at. Integer blandit lacus et ex faucibus imperdiet. Pellentesque vel arcu facilisis, tempor justo quis, scelerisque tellus. Morbi consectetur, mi eu tincidunt maximus, dolor magna sagittis velit, nec faucibus nibh mi quis tortor. Mauris a ex lorem. Maecenas interdum nibh facilisis orci convallis, vitae dictum felis euismod. Duis et mi id ante lacinia bibendum tempus id leo. Sed ac luctus nulla. Aliquam erat volutpat. Cras facilisis diam quis placerat tincidunt.

Duis ut iaculis lacus. Integer non mi tellus. Duis consectetur luctus dignissim. Nullam risus neque, condimentum et mollis vel, mattis ut dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec feugiat leo ut ullamcorper mollis. Curabitur accumsan iaculis porttitor. Mauris ornare molestie ullamcorper. Cras ac commodo neque. Duis tincidunt lobortis nulla, vel venenatis augue viverra ac. Vivamus pretium euismod sodales. Quisque tincidunt nec magna et accumsan.

Maecenas luctus ultricies orci ac laoreet. Praesent fringilla libero at diam bibendum congue. Morbi vel purus tincidunt, mollis lectus sit amet, lobortis dui. In venenatis, mi sed rhoncus scelerisque, arcu nulla posuere magna, ut lacinia ante nisi at tellus. Fusce vestibulum, nunc dignissim blandit accumsan, metus magna ornare magna, a convallis elit justo vitae urna. Phasellus sed leo vel nibh vestibulum bibendum. Mauris porta, lorem ac tempus aliquet, justo lorem aliquet lacus, a euismod felis orci ut lacus. Cras quis nisl quis erat euismod blandit eu eget nisl. Curabitur sodales accumsan odio, sed tincidunt libero. Sed ut faucibus ipsum. Donec fermentum fringilla sapien, in maximus tellus ultricies vel.

Curabitur sed erat egestas, scelerisque sapien mattis, bibendum neque. Proin volutpat fermentum quam, sit amet rutrum turpis pellentesque id. Aliquam porta lacinia purus, eu ullamcorper risus tincidunt quis. Maecenas commodo lectus in hendrerit convallis. Aliquam in libero pretium, faucibus eros quis, porttitor enim. Aliquam sit amet metus vitae urna euismod interdum eget in purus. Duis facilisis ornare sollicitudin.

Suspendisse nisi erat, ornare nec leo id, fringilla eleifend lectus. Mauris non nunc ac purus euismod volutpat. Integer tellus augue, condimentum nec consequat sit amet, auctor at dolor. Donec pulvinar molestie interdum. Phasellus at interdum dui. Curabitur et leo quis ante feugiat facilisis a ut neque. Praesent laoreet sodales magna. Ut pretium gravida sem, eu gravida est pellentesque ac. Pellentesque quis pharetra nisi. Integer at eleifend lorem. Suspendisse eget ultricies nibh. Suspendisse ut sapien posuere, tristique dui convallis, pharetra orci.

Pellentesque est dui, aliquam ac ipsum vitae, bibendum venenatis ex. Praesent id tempus est, ut vehicula massa. Fusce auctor ante non ex euismod ullamcorper. Cras suscipit augue ut urna volutpat, vel fringilla sapien feugiat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sed turpis maximus arcu aliquet feugiat at eu odio. Maecenas imperdiet, diam in bibendum sagittis, nunc odio aliquam nisl, a facilisis purus massa in erat. Nullam posuere neque ut sapien ullamcorper semper. Cras interdum, nisl vitae ornare sollicitudin, velit leo lobortis augue, id varius nisl enim ut tellus. Vestibulum augue tellus, condimentum in orci eget, faucibus volutpat lacus. Quisque id laoreet metus.

Donec vitae quam suscipit, porttitor nunc ut, placerat risus. Nullam rutrum mi sit amet ex malesuada auctor. Donec feugiat elit nec porta laoreet. Etiam feugiat orci eu nisi tempus aliquam et non justo. In viverra ex vel blandit ullamcorper. Nulla scelerisque felis eros. Nunc convallis odio ac mi tempor auctor. Fusce tincidunt metus porta ullamcorper aliquet. Donec ac auctor ipsum, non placerat felis. In cursus, ligula at pellentesque volutpat, nisi risus tristique dolor, non porttitor lectus diam vitae ex. Morbi vulputate purus et felis sollicitudin, non consectetur neque tempus. Sed fringilla, velit in placerat volutpat, metus sapien dictum dolor, quis gravida ipsum ipsum at lacus. Integer in arcu porta, sagittis lorem in, pulvinar nisi.

Aenean nec sem rhoncus, mollis nisi eu, vulputate magna. Cras nec dolor imperdiet, fermentum libero sed, iaculis erat. Maecenas id mauris ornare, gravida nisi quis, accumsan risus. Vivamus consectetur faucibus mi. Mauris commodo vitae augue et facilisis. Ut vel turpis purus. Maecenas cursus ex metus, eget imperdiet lorem commodo eget. Aliquam sodales felis nulla, et faucibus ex auctor vel.

Suspendisse pretium eu felis ut pulvinar. Sed luctus pharetra augue at iaculis. Maecenas ex nibh, suscipit ac lectus accumsan, ultrices scelerisque neque. Ut et orci dolor. Suspendisse consequat pulvinar ante dictum pellentesque. Integer egestas libero ac tristique gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla euismod vel ante ac vehicula. Donec vulputate ex luctus enim pretium pretium. Integer fringilla libero id justo consectetur, id egestas ipsum commodo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce luctus condimentum eros.

Sed molestie neque id elit luctus, posuere blandit nisi finibus. Nunc congue mauris iaculis, finibus purus a, pulvinar diam. Sed vitae mattis leo. Aenean pulvinar nisl neque, quis molestie elit consequat a. Integer et libero non lorem euismod finibus id ac elit. Aenean lacus nunc, faucibus sed faucibus vitae, vestibulum id ex. Cras volutpat eleifend massa ac sodales. Suspendisse dignissim in massa vestibulum tristique. Quisque posuere neque metus, eu malesuada turpis vestibulum sed. Etiam eu dui sollicitudin, porttitor tortor eget, varius ligula. Suspendisse accumsan rhoncus nisl in mollis. Nullam ligula metus, ornare vitae egestas imperdiet, vulputate vel mi. In hac habitasse platea dictumst. Aenean ligula lacus, maximus at molestie at, auctor vitae sapien.

In lacus nisi, mollis molestie venenatis vitae, sodales ac libero. In ut tortor et ipsum blandit egestas at eget metus. Etiam at ex purus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec lorem dui, accumsan at nisi non, molestie dictum velit. Duis vestibulum vitae arcu vitae imperdiet. Sed sed libero ac turpis tristique vestibulum. Nulla mollis, arcu non vehicula porttitor, tortor massa cursus libero, sed bibendum odio diam eu leo. Donec et nibh eu lectus sollicitudin pretium. Suspendisse viverra interdum nulla, nec efficitur ligula dictum ac. Cras placerat nisl eu tortor fermentum, eget tristique urna pretium.

Sed dictum ac augue a aliquam. Pellentesque consectetur mauris at lectus accumsan tempus. Integer eu felis eu ligula tincidunt blandit eget sit amet enim. Nam convallis porttitor risus, nec semper nibh pretium eget. Maecenas bibendum lacus vel quam mollis venenatis. Donec non auctor risus. Nulla nec ante quis nulla maximus ultricies. Proin sed neque non purus consectetur dapibus ut at nulla. Sed viverra, orci vel porttitor aliquet, enim diam lacinia ipsum, sit amet volutpat justo nulla eu metus. Donec in ex odio. Proin a porta odio, vel imperdiet dolor. In dictum quis diam ut aliquet. Donec urna quam, malesuada faucibus ipsum id, consectetur euismod leo.

Aenean mattis aliquet nunc, vel condimentum ex auctor vitae. Sed at dapibus dolor. Vestibulum a ullamcorper nunc. Pellentesque sodales neque porta lacus elementum porta. Pellentesque quis neque fermentum libero maximus imperdiet quis sit amet enim. Nullam sed tristique elit, quis posuere dolor. Etiam vitae commodo urna. Cras id felis ultrices, congue leo quis, volutpat nisl. Suspendisse lacus ligula, imperdiet ac facilisis molestie, accumsan eu velit.

In ac felis et nunc pretium auctor. Quisque et felis posuere, bibendum enim sed, finibus nisl. Donec tellus leo, feugiat at vestibulum a, accumsan eget elit. Nam pulvinar dolor metus, vitae faucibus ipsum maximus vitae. Morbi erat libero, condimentum ut aliquam id, fermentum eu lacus. Curabitur a magna a odio consectetur vestibulum sed a neque. Praesent commodo elit sit amet felis eleifend, vitae volutpat arcu interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam erat volutpat. Fusce volutpat, erat non vestibulum placerat, tellus lectus sodales tortor, in elementum elit ipsum eu lectus. In in ligula non diam malesuada ullamcorper. Sed tristique erat nec augue vulputate, nec iaculis sapien consectetur.

Curabitur ex orci, luctus vel consequat nec, pellentesque sed massa. Sed imperdiet nibh ultrices sapien varius vehicula. Nunc dignissim eu diam ac tincidunt. Nunc faucibus non augue tristique pretium. Fusce vel mollis nisi. Duis sit amet neque varius, aliquam quam non, egestas tortor. Pellentesque eget ipsum quis odio luctus faucibus ut at elit. Nulla sed condimentum diam. Phasellus sit amet dapibus elit, posuere eleifend velit. Sed viverra consectetur neque. Nam sapien tortor, dapibus quis sagittis nec, tempor nec augue. Vestibulum sollicitudin sem sit amet enim pharetra facilisis.

Phasellus malesuada, mauris pellentesque finibus egestas, elit felis consectetur erat, in malesuada erat elit ut augue. Vestibulum nec convallis augue. Pellentesque justo felis, eleifend vitae porttitor eget, tristique vel sapien. Nunc tempus rhoncus nisl. Etiam vulputate massa ut urna cursus, ac dapibus nunc ullamcorper. Vestibulum sit amet pretium lorem, vel semper mi. Proin placerat efficitur placerat. Duis id congue tellus, quis porta enim. Nullam in odio magna. Ut ullamcorper scelerisque enim, ut laoreet sem fringilla vel. Aliquam faucibus enim purus, sit amet dictum justo dictum nec. Praesent at purus non velit volutpat finibus. Suspendisse dignissim diam sem. Nullam in placerat urna. Duis finibus metus facilisis neque ultricies molestie. Maecenas risus enim, blandit sit amet auctor eget, vulputate ut risus.

Maecenas posuere ipsum vel lacus molestie convallis. In velit massa, molestie eu sollicitudin eget, commodo dignissim risus. Etiam mauris leo, lacinia vel arcu eu, faucibus suscipit quam. Mauris interdum dui id nibh rutrum ornare. In vitae consectetur est, ac rhoncus risus. Fusce quam lacus, venenatis non dapibus sed, efficitur eget elit. Donec faucibus eros ac mi facilisis semper. Cras ac porttitor enim, sit amet gravida sem. Praesent mattis vehicula mi non facilisis. Praesent eu elit ultrices, suscipit purus a, tempus velit. Praesent sed blandit mauris. Nullam et metus vitae ante ultricies aliquet.

Donec id faucibus mi. Ut id scelerisque nulla, vitae imperdiet nisl. Nullam luctus, nisl sed posuere hendrerit, urna augue porttitor ligula, sit amet feugiat nisl purus et dolor. Donec rutrum mi at elit pretium efficitur. Nunc convallis velit non augue auctor congue. Donec porta dolor mi, lacinia sollicitudin augue efficitur vitae. Praesent at eros in urna pretium aliquam vitae sed ipsum.

Fusce eleifend ligula eu ultricies vehicula. In hac habitasse platea dictumst. Curabitur consequat posuere justo, nec egestas urna rhoncus quis. Cras nunc turpis, ultricies in odio vitae, tempor interdum erat. Donec congue turpis luctus, euismod mauris ut, congue odio. Aenean elit elit, dictum sed laoreet in, laoreet rhoncus nibh. Nulla nibh massa, tempus sit amet porttitor vitae, condimentum nec magna.

Maecenas scelerisque vitae mauris id commodo. Quisque venenatis est ipsum, a volutpat nisi dignissim ut. Integer at gravida purus, et ullamcorper nunc. Quisque a sem elementum, elementum ex et, sollicitudin urna. Donec sodales porta odio, a lacinia metus vestibulum non. Quisque consequat, lorem eu pellentesque consequat, nunc nunc pellentesque lorem, at auctor dolor velit eget urna. Duis ut mattis ligula. Suspendisse potenti. Aliquam id libero ex. Donec at fermentum dolor. Vivamus accumsan quam et mauris laoreet pharetra. Sed fringilla ullamcorper justo a pulvinar. Sed pulvinar dignissim odio, nec tempus dolor volutpat at. Vestibulum faucibus vel est eget feugiat. Nam pellentesque hendrerit ipsum a ullamcorper.

Cras auctor sem eget faucibus convallis. Vivamus egestas dictum metus, nec auctor nisi consectetur sed. Aliquam id aliquet justo. Cras felis libero, aliquet nec nibh et, eleifend hendrerit quam. Ut at nisi viverra, venenatis nibh sit amet, ullamcorper dui. Nulla facilisi. Duis placerat id odio quis laoreet. Duis fringilla nisi ut feugiat pharetra. In rhoncus aliquam purus eu commodo. Aenean sollicitudin pellentesque nunc, in lacinia massa fermentum vitae. Aliquam quis ultrices felis. Maecenas dapibus metus at lobortis vestibulum. Ut feugiat, dui eget cursus varius, lacus ex varius metus, et accumsan orci dui ut erat.

Aenean non tempus quam, a fermentum nulla. Nulla tincidunt orci ac sem rhoncus, eu euismod orci convallis. Nam imperdiet mi ut auctor sagittis. Donec venenatis lacus sit amet ligula hendrerit, a scelerisque risus posuere. Ut consectetur magna arcu, sed rhoncus diam ultricies et. Nulla sollicitudin posuere tincidunt. Suspendisse in laoreet magna. Nulla facilisi. Duis ut nulla at augue maximus eleifend eget at ex. Nullam ipsum nunc, faucibus eget luctus eu, dapibus eu risus. Maecenas ac quam vitae metus rutrum pretium. Phasellus eget ornare lectus. Sed enim ligula, posuere blandit eros interdum, feugiat ornare massa.

Donec lobortis massa lacus, feugiat consectetur magna sollicitudin nec. Suspendisse gravida interdum dolor, vel tincidunt nulla condimentum sit amet. Maecenas eu luctus diam. Curabitur lacinia imperdiet magna vitae placerat. Curabitur convallis tortor sed justo interdum iaculis. Duis orci ante, dapibus ut ultricies a, interdum eu tellus. Nulla commodo sagittis mi id condimentum. Maecenas sit amet feugiat sem. Maecenas venenatis nulla felis, nec ultricies augue laoreet vitae. Maecenas commodo non tellus eu dignissim. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum at justo consectetur, dictum orci quis, consectetur nisl. Fusce in ante ac felis vulputate interdum.

Integer laoreet, sem vitae placerat tincidunt, ligula neque ultrices ante, eu dapibus dui velit aliquet diam. Duis sit amet nunc eget leo posuere efficitur vitae eget lacus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin vel ante ornare, dictum lacus nec, faucibus libero. Duis ultrices ligula lobortis neque eleifend interdum. Aenean eu risus eu ipsum aliquet imperdiet quis at enim. Mauris sed aliquet lorem. Morbi aliquam arcu at risus consectetur tempus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi lectus urna, suscipit non pretium id, tristique rutrum nulla. Maecenas pulvinar tempus felis, at volutpat risus placerat eu. Sed elementum libero cursus congue pharetra. Vestibulum quis tellus nibh.

In sodales, elit eget dignissim posuere, nunc erat ultricies magna, ac imperdiet lectus nibh sed sapien. In tempor bibendum velit non molestie. Donec sit amet nisl at leo bibendum molestie. Quisque eget nisl viverra, tincidunt ex id, rhoncus metus. Suspendisse quis nulla porta, consequat est ac, mollis ex. Proin sit amet turpis ornare, pulvinar leo nec, tincidunt dolor. Phasellus hendrerit orci vitae iaculis luctus. Mauris in tellus ipsum. Aliquam finibus neque congue tempor bibendum. Duis id nisl nulla. Vivamus augue dolor, tincidunt vel tortor rhoncus, tempus fringilla nulla. Nunc eget diam dignissim, semper arcu a, sodales tellus.

Phasellus elit sem, tristique sit amet auctor quis, porta ut est. Ut elit velit, posuere fringilla rhoncus eu, posuere egestas eros. Vestibulum ut sapien sit amet purus tincidunt convallis. Sed nec orci pharetra turpis porta volutpat eu sit amet risus. Curabitur varius vulputate magna. Suspendisse pellentesque tellus non nibh euismod euismod. Nulla a vestibulum nisi, a vehicula magna.

Duis pulvinar et velit eget vulputate. Maecenas id tincidunt massa. Mauris condimentum fringilla ipsum, ut dignissim mauris aliquet tempor. Praesent consectetur tempor hendrerit. Sed condimentum et mauris vel bibendum. Quisque arcu velit, feugiat nec blandit ac, aliquet a orci. Etiam sit amet ornare ante. Phasellus nec tincidunt leo. Nulla facilisi. Suspendisse eget lorem sed dui pellentesque molestie id auctor nisi. Integer rutrum sem et tempor tempus. Sed gravida suscipit laoreet. Nullam convallis urna vitae nisi auctor, id volutpat lorem volutpat. Sed vel urna convallis eros dapibus cursus. Sed at nisi ac felis euismod vestibulum.

Aliquam nisi lectus, finibus non justo a, porta facilisis ligula. Maecenas consequat sapien sed volutpat porttitor. Morbi tellus ligula, fringilla eu velit ac, maximus congue felis. Nunc quis porttitor mauris. Integer non imperdiet ante. Sed venenatis fringilla neque. Pellentesque euismod, risus vel eleifend mattis, risus nibh tempus augue, tempus laoreet nunc justo eu est. Cras iaculis lorem ac blandit lobortis. Nam quis ipsum ac risus semper porttitor. Proin commodo commodo ante a euismod. Ut luctus id mi in consequat. Sed ullamcorper sapien at dui suscipit, vel eleifend odio feugiat. Duis dolor sem, lacinia eget risus at, bibendum mattis urna. Sed gravida porta odio eu sollicitudin. Sed vel libero in risus pellentesque sollicitudin. Donec ligula purus, consequat vitae mauris eu, iaculis maximus enim.

Suspendisse accumsan nulla et tortor lobortis sagittis. Ut efficitur tincidunt porttitor. Nullam fermentum eleifend dapibus. Aenean viverra ultrices lectus, quis semper tellus. Aliquam magna nunc, scelerisque sit amet pretium eu, vehicula sit amet felis. In purus eros, rhoncus eu semper nec, sodales nec ligula. Sed vehicula eros in dui aliquet venenatis. Phasellus venenatis lobortis sapien eget tempus. Praesent sed sodales risus, vel euismod turpis. Integer vel efficitur lacus. Suspendisse quis molestie odio, et aliquet neque. Etiam bibendum lorem et nunc lacinia malesuada. Aliquam porttitor tristique aliquet. Donec non est enim. Sed imperdiet urna vitae erat laoreet, eu lacinia nulla pharetra. Phasellus vulputate eleifend semper. Etiam maximus quis erat nec.';